version: '3'

services:
  db:
    image: postgres:${POSTGRES_TAG:-latest}
    shm_size: 1gb
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: concourse
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev

  web:
    build: .
    image: concourse/concourse:local
    volumes:
    - .:/src
    command: web
    depends_on: [db]
    ports:
    - 8080:8080
    environment:
      CONCOURSE_ADD_LOCAL_USER: test:test,guest:guest
      CONCOURSE_CLUSTER_NAME: dev
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_ENABLE_LIDAR: 'true'
      CONCOURSE_LOG_LEVEL: debug
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: dev
      CONCOURSE_POSTGRES_PASSWORD: dev
      CONCOURSE_ENABLE_ACROSS_STEP: "true"
      CONCOURSE_KUBERNETES_WORKER_KUBECONFIG: kind/kubeconfig.yml