version: '3'

services:
  worker:
    environment:
      # so that CI can configure a different network range that doesn't overlap
      # with the outer Garden
      CONCOURSE_GARDEN_NETWORK_POOL: '10.224.0.0/16'
