---
platform: linux

image_resource:
  type: registry-image
  source: {repository: concourse/unit}

inputs:
- name: version

outputs:
- name: tags

params:
  LATEST:

run:
  path: bash
  args:
  - -exc
  - |
    version=$(cat version/version)
    echo $version | cut -d. -f1,2,3 >> tags/tags
    echo $version | cut -d. -f1,2   >> tags/tags

    if [ "$LATEST" = "true" ]; then
      # when pushing a patch for an old version, you won't want to bump the
      # major or latest tag, so this should be opt-in
      echo $version | cut -d. -f1   >> tags/tags

      echo latest >> tags/tags
    fi
