image: cirocosta/concourse
imageDigest: sha256:cd09d181a016db729006bf0e26d94acc7c782cc9fcacdf5da4464dd540971977

web:
  env:
    - name: CONCOURSE_KUBERNETES_WORKER_SERVICE_ACCOUNT
      value: /var/run/secrets/kubernetes.io/serviceaccount

concourse:
  web:
    externalUrl: http://localhost:8080
    kubernetes:
      enabled: true
      keepNamespaces: false

worker:
  enabled: false

